name: On Push Message

on:
  push:
    branches:
      - main  # or whatever branch you want

jobs:
  Sonar Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print push message
        run: echo "You pushed something."
